apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: demovisitorservice
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: demovisitorservice
  targetCPUUtilizationPercentage: 60
