apiVersion: v1
kind: Pod
metadata:
  name: demoapiservice
  namespace: default
  labels:
    app: demoapiservice
spec:
  containers:
  - name: demoapiservice
    image: demoapiservice:1.0
    resources:
      limits:
        memory: "250Mi"
      requests:
        memory: "100Mi"
